/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SimpleText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & PullQuote)
  | ({
      _key: string;
    } & Chart)
>;

export type Chart = {
  _type: "chart";
  type?: "bar" | "line";
  title?: string;
  data?: Array<{
    label?: string;
    value?: number;
    _type: "dataPoint";
    _key: string;
  }>;
};

export type PullQuote = {
  _type: "pullQuote";
  quote?: string;
  attribution?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  topic?: TopicReference;
  author?: AuthorReference;
  coverStyle?: "bars" | "circles" | "squares" | "triangle" | "line" | "rings";
  publishedAt?: string;
  readTime?: number;
  featured?: boolean;
  body?: RichText;
  seo?: Seo;
  isSample?: boolean;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  abstract?: string;
  coverStyle?: "bars" | "circles" | "squares" | "triangle" | "line" | "rings";
  topic?: TopicReference;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  publishedAt?: string;
  featured?: boolean;
  keyFindings?: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }>;
  body?: RichText;
  methodology?: SimpleText;
  sources?: Array<{
    title?: string;
    url?: string;
    _type: "source";
    _key: string;
  }>;
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  seo?: Seo;
  isSample?: boolean;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  colorKey?: "accent" | "teal" | "plum" | "mustard" | "ink";
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SimpleText
  | SanityImageAssetReference
  | RichText
  | Chart
  | PullQuote
  | Seo
  | TopicReference
  | AuthorReference
  | Article
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Report
  | Topic
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: featuredReportQuery
// Query: *[_type == "report" && featured == true && defined(slug.current)]    | order(publishedAt desc)[0]{   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey }, keyFindings }
export type FeaturedReportQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  keyFindings: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }> | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: latestReportsQuery
// Query: *[_type == "report" && defined(slug.current)]    | order(publishedAt desc)[0...$limit]{   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type LatestReportsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: reportBySlugQuery
// Query: *[_type == "report" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey },    authors[]->{ _id, name, "slug": slug.current, role, photo, bio },    keyFindings,    body,    methodology,    sources,    "pdfUrl": pdf.asset->url,    seo,    isSample  }
export type ReportBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  authors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: string | null;
  }> | null;
  keyFindings: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }> | null;
  body: RichText | null;
  methodology: SimpleText | null;
  sources: Array<{
    title?: string;
    url?: string;
    _type: "source";
    _key: string;
  }> | null;
  pdfUrl: string | null;
  seo: Seo | null;
  isSample: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: reportsByTopicQuery
// Query: *[_type == "report" && topic->slug.current == $topic && defined(slug.current)]    | order(publishedAt desc){   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type ReportsByTopicQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: latestArticlesQuery
// Query: *[_type == "article" && defined(slug.current)]    | order(publishedAt desc)[0...$limit]{   _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current } }
export type LatestArticlesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current },    author->{ _id, name, "slug": slug.current, role, photo, bio },    body,    seo,    isSample  }
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
  body: RichText | null;
  seo: Seo | null;
  isSample: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: allTopicsQuery
// Query: *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current, colorKey, description }
export type AllTopicsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  description: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "report" && featured == true && defined(slug.current)]\n    | order(publishedAt desc)[0]{ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n, keyFindings }\n': FeaturedReportQueryResult;
    '\n  *[_type == "report" && defined(slug.current)]\n    | order(publishedAt desc)[0...$limit]{ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': LatestReportsQueryResult;
    '\n  *[_type == "report" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n,\n    authors[]->{ _id, name, "slug": slug.current, role, photo, bio },\n    keyFindings,\n    body,\n    methodology,\n    sources,\n    "pdfUrl": pdf.asset->url,\n    seo,\n    isSample\n  }\n': ReportBySlugQueryResult;
    '\n  *[_type == "report" && topic->slug.current == $topic && defined(slug.current)]\n    | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': ReportsByTopicQueryResult;
    '\n  *[_type == "article" && defined(slug.current)]\n    | order(publishedAt desc)[0...$limit]{ \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n }\n': LatestArticlesQueryResult;
    '\n  *[_type == "article" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n,\n    author->{ _id, name, "slug": slug.current, role, photo, bio },\n    body,\n    seo,\n    isSample\n  }\n': ArticleBySlugQueryResult;
    '\n  *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current, colorKey, description }\n': AllTopicsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
