/**
 * Query result and schema types, generated by Sanity TypeGen (`pnpm typegen`).
 * Import from here rather than the generated file.
 */
import type {
  ArticleBySlugQueryResult,
  LatestArticlesQueryResult,
  LatestReportsQueryResult,
  ReportBySlugQueryResult,
} from "./types.generated";

export type {
  AboutPageQueryResult,
  AllTopicsQueryResult,
  ArticleBySlugQueryResult,
  ArticlesListQueryResult,
  ContactPageQueryResult,
  HomePageQueryResult,
  ServiceBySlugQueryResult,
  ServicesQueryResult,
  SiteSettingsQueryResult,
  Chart,
  FeaturedReportQueryResult,
  FeaturedWorkQueryResult,
  LatestArticlesQueryResult,
  LatestReportsQueryResult,
  PullQuote,
  RelatedArticlesQueryResult,
  RelatedReportsQueryResult,
  ReportBySlugQueryResult,
  ReportsByTopicQueryResult,
  ReportsListQueryResult,
  RichText,
  SimpleText,
} from "./types.generated";

export type ReportCardData = NonNullable<LatestReportsQueryResult[number]>;
export type ArticleCardData = NonNullable<LatestArticlesQueryResult[number]>;
export type ReportDetail = NonNullable<ReportBySlugQueryResult>;
export type ArticleDetail = NonNullable<ArticleBySlugQueryResult>;
export type AuthorDetail = NonNullable<ReportDetail["authors"]>[number];
export type ServiceCardData = NonNullable<import("./types.generated").ServicesQueryResult[number]>;
export type SiteSettings = NonNullable<import("./types.generated").SiteSettingsQueryResult>;
