/**
 * Query result types, generated by Sanity TypeGen (`pnpm typegen`).
 * Import from here rather than the generated file.
 */
export type {
  AllTopicsQueryResult,
  ArticleBySlugQueryResult,
  FeaturedReportQueryResult,
  LatestArticlesQueryResult,
  LatestReportsQueryResult,
  ReportBySlugQueryResult,
  ReportsByTopicQueryResult,
} from "./types.generated";

export type ReportCardData = NonNullable<import("./types.generated").LatestReportsQueryResult[number]>;
export type ArticleCardData = NonNullable<import("./types.generated").LatestArticlesQueryResult[number]>;
