/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SimpleText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & PullQuote)
  | ({
      _key: string;
    } & Chart)
>;

export type Chart = {
  _type: "chart";
  type?: "bar" | "line";
  title?: string;
  data?: Array<{
    label?: string;
    value?: number;
    _type: "dataPoint";
    _key: string;
  }>;
};

export type PullQuote = {
  _type: "pullQuote";
  quote?: string;
  attribution?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  colorKey?: "accent" | "teal" | "plum" | "mustard" | "ink";
  coverStyle?: "bars" | "circles" | "squares" | "triangle" | "line" | "rings";
  deliverables?: Array<string>;
  body?: RichText;
  order?: number;
  seo?: Seo;
  isSample?: boolean;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  topic?: TopicReference;
  author?: AuthorReference;
  coverStyle?: "bars" | "circles" | "squares" | "triangle" | "line" | "rings";
  publishedAt?: string;
  readTime?: number;
  featured?: boolean;
  body?: RichText;
  seo?: Seo;
  isSample?: boolean;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Report = {
  _id: string;
  _type: "report";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  subtitle?: string;
  abstract?: string;
  coverStyle?: "bars" | "circles" | "squares" | "triangle" | "line" | "rings";
  topic?: TopicReference;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  publishedAt?: string;
  featured?: boolean;
  keyFindings?: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }>;
  body?: RichText;
  methodology?: SimpleText;
  sources?: Array<{
    title?: string;
    url?: string;
    _type: "source";
    _key: string;
  }>;
  pdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  seo?: Seo;
  isSample?: boolean;
};

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  colorKey?: "accent" | "teal" | "plum" | "mustard" | "ink";
  description?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  positioning?: string;
  ctaLabel?: string;
  capabilityPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  email?: string;
  phone?: string;
  address?: string;
  officeHours?: string;
  socials?: Array<{
    label?: string;
    url?: string;
    _type: "social";
    _key: string;
  }>;
  copyright?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  intro?: string;
  topics?: Array<string>;
  successMessage?: string;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  intro?: string;
  story?: SimpleText;
  values?: Array<{
    title?: string;
    text?: string;
    _type: "value";
    _key: string;
  }>;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  teamHeading?: string;
  team?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  headline?: string;
  intro?: string;
  primaryCta?: string;
  secondaryCta?: string;
  availability?: string;
  trustFacts?: Array<string>;
  marquee?: Array<string>;
  whoHeading?: string;
  whoBody?: string;
  whoQuote?: string;
  whoQuoteAttribution?: string;
  founderQuote?: string;
  founderName?: string;
  founderRole?: string;
  numbersHeading?: string;
  numbers?: Array<{
    value?: string;
    label?: string;
    _type: "figure";
    _key: string;
  }>;
  commitmentsHeading?: string;
  commitments?: Array<{
    title?: string;
    text?: string;
    _type: "commitment";
    _key: string;
  }>;
  statementHeading?: string;
  statementText?: string;
  stepsHeading?: string;
  steps?: Array<{
    label?: string;
    title?: string;
    text?: string;
    _type: "step";
    _key: string;
  }>;
  ctaHeading?: string;
  ctaText?: string;
  insightsHeading?: string;
  servicesHeading?: string;
  areasHeading?: string;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SimpleText
  | SanityImageAssetReference
  | RichText
  | Chart
  | PullQuote
  | Seo
  | Service
  | TopicReference
  | AuthorReference
  | Article
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Report
  | Topic
  | SiteSettings
  | ContactPage
  | AboutPage
  | HomePage
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/adminQueries.ts
// Variable: adminStatsQuery
// Query: {  "reports": {    "total": count(*[_type == "report"]),    "recent": count(*[_type == "report" && _createdAt > $since]),    "previous": count(*[_type == "report" && _createdAt > $prevSince && _createdAt <= $since])  },  "articles": {    "total": count(*[_type == "article"]),    "recent": count(*[_type == "article" && _createdAt > $since]),    "previous": count(*[_type == "article" && _createdAt > $prevSince && _createdAt <= $since])  },  "services": {    "total": count(*[_type == "service"]),    "recent": count(*[_type == "service" && _createdAt > $since]),    "previous": count(*[_type == "service" && _createdAt > $prevSince && _createdAt <= $since])  },  "images": {    "total": count(*[_type == "sanity.imageAsset"]),    "recent": count(*[_type == "sanity.imageAsset" && _createdAt > $since]),    "previous": count(*[_type == "sanity.imageAsset" && _createdAt > $prevSince && _createdAt <= $since])  }}
export type AdminStatsQueryResult = {
  reports: {
    total: number;
    recent: number;
    previous: number;
  };
  articles: {
    total: number;
    recent: number;
    previous: number;
  };
  services: {
    total: number;
    recent: number;
    previous: number;
  };
  images: {
    total: number;
    recent: number;
    previous: number;
  };
};

// Source: src/sanity/adminQueries.ts
// Variable: adminActivityQuery
// Query: *[_type in ["report", "article", "service", "author", "topic", "homePage", "aboutPage", "contactPage", "siteSettings", "sanity.imageAsset"] && _updatedAt > $since]{ _type, _updatedAt }
export type AdminActivityQueryResult = Array<
  | {
      _type: "aboutPage";
      _updatedAt: string;
    }
  | {
      _type: "article";
      _updatedAt: string;
    }
  | {
      _type: "author";
      _updatedAt: string;
    }
  | {
      _type: "contactPage";
      _updatedAt: string;
    }
  | {
      _type: "homePage";
      _updatedAt: string;
    }
  | {
      _type: "report";
      _updatedAt: string;
    }
  | {
      _type: "sanity.imageAsset";
      _updatedAt: string;
    }
  | {
      _type: "service";
      _updatedAt: string;
    }
  | {
      _type: "siteSettings";
      _updatedAt: string;
    }
  | {
      _type: "topic";
      _updatedAt: string;
    }
>;

// Source: src/sanity/adminQueries.ts
// Variable: adminTopicBreakdownQuery
// Query: *[_type == "topic"]{    _id, title, colorKey,    "reports": count(*[_type == "report" && references(^._id)]),    "articles": count(*[_type == "article" && references(^._id)])  } | order((reports + articles) desc, title asc)
export type AdminTopicBreakdownQueryResult = Array<{
  _id: string;
  title: string | null;
  colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  reports: number;
  articles: number;
}>;

// Source: src/sanity/adminQueries.ts
// Variable: adminRecentQuery
// Query: *[_type in ["report", "article", "service", "author", "topic"]] | order(_updatedAt desc)[0...$limit]{   _id, _type, _updatedAt, _createdAt,  "title": coalesce(title, name),  "slug": slug.current,  featured, isSample, publishedAt,  "topic": topic->{ title, colorKey },  "people": coalesce(authors[]->name, [author->name]) }
export type AdminRecentQueryResult = Array<
  | {
      _id: string;
      _type: "article";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<string | null>;
    }
  | {
      _id: string;
      _type: "author";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
  | {
      _id: string;
      _type: "report";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<null> | Array<string | null>;
    }
  | {
      _id: string;
      _type: "service";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: boolean | null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
  | {
      _id: string;
      _type: "topic";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
>;

// Source: src/sanity/adminQueries.ts
// Variable: adminListQuery
// Query: *[_type == $type] | order(_updatedAt desc){   _id, _type, _updatedAt, _createdAt,  "title": coalesce(title, name),  "slug": slug.current,  featured, isSample, publishedAt,  "topic": topic->{ title, colorKey },  "people": coalesce(authors[]->name, [author->name]), "count": count(*[references(^._id)]) }
export type AdminListQueryResult = Array<
  | {
      _id: string;
      _type: "aboutPage";
      _updatedAt: string;
      _createdAt: string;
      title: null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "article";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<string | null>;
      count: number;
    }
  | {
      _id: string;
      _type: "author";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "contactPage";
      _updatedAt: string;
      _createdAt: string;
      title: null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "homePage";
      _updatedAt: string;
      _createdAt: string;
      title: null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "media.folder";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "media.tag";
      _updatedAt: string;
      _createdAt: string;
      title: Slug | null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "report";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<null> | Array<string | null>;
      count: number;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "service";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: boolean | null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "siteSettings";
      _updatedAt: string;
      _createdAt: string;
      title: null;
      slug: null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
  | {
      _id: string;
      _type: "topic";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
      count: number;
    }
>;

// Source: src/sanity/adminQueries.ts
// Variable: adminMediaQuery
// Query: *[_type == "sanity.imageAsset"] | order(_createdAt desc){    _id, url, originalFilename, size, extension, _createdAt,    "width": metadata.dimensions.width, "height": metadata.dimensions.height,    "usedBy": count(*[references(^._id)])  }
export type AdminMediaQueryResult = Array<{
  _id: string;
  url: string | null;
  originalFilename: string | null;
  size: number | null;
  extension: string | null;
  _createdAt: string;
  width: number | null;
  height: number | null;
  usedBy: number;
}>;

// Source: src/sanity/adminQueries.ts
// Variable: adminPagesQuery
// Query: *[_id in ["homePage", "aboutPage", "contactPage", "siteSettings"]]{ _id, _type, _updatedAt }
export type AdminPagesQueryResult = Array<
  | {
      _id: string;
      _type: "aboutPage";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "article";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "author";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "contactPage";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "homePage";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "media.folder";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "media.tag";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "report";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "sanity.fileAsset";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "sanity.imageAsset";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "service";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "siteSettings";
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "topic";
      _updatedAt: string;
    }
>;

// Source: src/sanity/adminQueries.ts
// Variable: adminSearchQuery
// Query: *[_type in ["report", "article", "service", "author", "topic"] && [coalesce(title, name), pt::text(body), summary, excerpt, abstract] match $q]    | order(_updatedAt desc)[0...30]{   _id, _type, _updatedAt, _createdAt,  "title": coalesce(title, name),  "slug": slug.current,  featured, isSample, publishedAt,  "topic": topic->{ title, colorKey },  "people": coalesce(authors[]->name, [author->name]) }
export type AdminSearchQueryResult = Array<
  | {
      _id: string;
      _type: "article";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<string | null>;
    }
  | {
      _id: string;
      _type: "author";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
  | {
      _id: string;
      _type: "report";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: boolean | null;
      isSample: boolean | null;
      publishedAt: string | null;
      topic: {
        title: string | null;
        colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
      } | null;
      people: Array<null> | Array<string | null>;
    }
  | {
      _id: string;
      _type: "service";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: boolean | null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
  | {
      _id: string;
      _type: "topic";
      _updatedAt: string;
      _createdAt: string;
      title: string | null;
      slug: string | null;
      featured: null;
      isSample: null;
      publishedAt: null;
      topic: null;
      people: Array<null>;
    }
>;

// Source: src/sanity/queries.ts
// Variable: featuredReportQuery
// Query: coalesce(    *[_type == "report" && featured == true && defined(slug.current)] | order(publishedAt desc)[0],    *[_type == "report" && defined(slug.current)] | order(publishedAt desc)[0]  ){   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey }, keyFindings, "pdfUrl": pdf.asset->url }
export type FeaturedReportQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  keyFindings: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }> | null;
  pdfUrl: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: latestReportsQuery
// Query: *[_type == "report" && defined(slug.current)]    | order(publishedAt desc)[0...$limit]{   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type LatestReportsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: reportBySlugQuery
// Query: *[_type == "report" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey },    "topicId": topic._ref,    authors[]->{ _id, name, "slug": slug.current, role, photo, bio },    keyFindings,    body,    methodology,    sources,    "pdfUrl": pdf.asset->url,    seo,    isSample  }
export type ReportBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  topicId: string | null;
  authors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: string | null;
  }> | null;
  keyFindings: Array<{
    value?: string;
    label?: string;
    _type: "finding";
    _key: string;
  }> | null;
  body: RichText | null;
  methodology: SimpleText | null;
  sources: Array<{
    title?: string;
    url?: string;
    _type: "source";
    _key: string;
  }> | null;
  pdfUrl: string | null;
  seo: Seo | null;
  isSample: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: reportsByTopicQuery
// Query: *[_type == "report" && topic->slug.current == $topic && defined(slug.current)]    | order(publishedAt desc){   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type ReportsByTopicQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: latestArticlesQuery
// Query: *[_type == "article" && defined(slug.current)]    | order(publishedAt desc)[0...$limit]{   _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current } }
export type LatestArticlesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current },    "topicId": topic._ref,    author->{ _id, name, "slug": slug.current, role, photo, bio },    body,    seo,    isSample  }
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
  topicId: string | null;
  body: RichText | null;
  seo: Seo | null;
  isSample: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: allTopicsQuery
// Query: *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current, colorKey, description }
export type AllTopicsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  description: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: reportsListQuery
// Query: *[_type == "report" && defined(slug.current) && (!defined($topic) || topic->slug.current == $topic)]    | order(publishedAt desc){   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type ReportsListQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: relatedReportsQuery
// Query: *[_type == "report" && defined(slug.current) && _id != $id && topic._ref == $topicId]    | order(publishedAt desc)[0...3]{   _id,  title,  "slug": slug.current,  subtitle,  abstract,  coverStyle,  publishedAt,  featured,  // Estimated from body length at ~220 words per minute.  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,  topic->{ _id, title, "slug": slug.current, colorKey } }
export type RelatedReportsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  abstract: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  featured: boolean | null;
  readTime: number;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: reportSlugsQuery
// Query: *[_type == "report" && defined(slug.current)].slug.current
export type ReportSlugsQueryResult = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: articlesListQuery
// Query: *[_type == "article" && defined(slug.current) && (!defined($topic) || topic->slug.current == $topic)]    | order(publishedAt desc){   _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current } }
export type ArticlesListQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: relatedArticlesQuery
// Query: *[_type == "article" && defined(slug.current) && _id != $id]    | order(select(topic._ref == $topicId => 1, 0) desc, publishedAt desc)[0...3]{   _id,  title,  "slug": slug.current,  excerpt,  coverStyle,  publishedAt,  readTime,  featured,  topic->{ _id, title, "slug": slug.current, colorKey },  author->{ name, "slug": slug.current } }
export type RelatedArticlesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  publishedAt: string | null;
  readTime: number | null;
  featured: boolean | null;
  topic: {
    _id: string;
    title: string | null;
    slug: string | null;
    colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: articleSlugsQuery
// Query: *[_type == "article" && defined(slug.current)].slug.current
export type ArticleSlugsQueryResult = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    siteName, positioning, ctaLabel, email, phone, address, officeHours, socials[]{ _key, label, url }, copyright,    "capabilityPdfUrl": capabilityPdf.asset->url  }
export type SiteSettingsQueryResult = {
  siteName: string | null;
  positioning: string | null;
  ctaLabel: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  officeHours: string | null;
  socials: Array<{
    _key: string;
    label: string | null;
    url: string | null;
  }> | null;
  copyright: string | null;
  capabilityPdfUrl: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{    eyebrow, headline, intro, primaryCta, secondaryCta, availability, trustFacts, marquee,    whoHeading, whoBody, whoQuote, whoQuoteAttribution,    founderQuote, founderName, founderRole,    numbersHeading, numbers[]{ _key, value, label },    commitmentsHeading, commitments[]{ _key, title, text },    statementHeading, statementText,    stepsHeading, steps[]{ _key, label, title, text },    ctaHeading, ctaText,    insightsHeading, servicesHeading, areasHeading, newsletterHeading, newsletterText, seo  }
export type HomePageQueryResult = {
  eyebrow: string | null;
  headline: string | null;
  intro: string | null;
  primaryCta: string | null;
  secondaryCta: string | null;
  availability: string | null;
  trustFacts: Array<string> | null;
  marquee: Array<string> | null;
  whoHeading: string | null;
  whoBody: string | null;
  whoQuote: string | null;
  whoQuoteAttribution: string | null;
  founderQuote: string | null;
  founderName: string | null;
  founderRole: string | null;
  numbersHeading: string | null;
  numbers: Array<{
    _key: string;
    value: string | null;
    label: string | null;
  }> | null;
  commitmentsHeading: string | null;
  commitments: Array<{
    _key: string;
    title: string | null;
    text: string | null;
  }> | null;
  statementHeading: string | null;
  statementText: string | null;
  stepsHeading: string | null;
  steps: Array<{
    _key: string;
    label: string | null;
    title: string | null;
    text: string | null;
  }> | null;
  ctaHeading: string | null;
  ctaText: string | null;
  insightsHeading: string | null;
  servicesHeading: string | null;
  areasHeading: string | null;
  newsletterHeading: string | null;
  newsletterText: string | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    headline, intro, story, values[]{ _key, title, text }, stats[]{ _key, value, label }, teamHeading,    team[]->{ _id, name, "slug": slug.current, role, photo, bio },    seo  }
export type AboutPageQueryResult = {
  headline: string | null;
  intro: string | null;
  story: SimpleText | null;
  values: Array<{
    _key: string;
    title: string | null;
    text: string | null;
  }> | null;
  stats: Array<{
    _key: string;
    value: string | null;
    label: string | null;
  }> | null;
  teamHeading: string | null;
  team: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    bio: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{ headline, intro, topics, successMessage, seo }
export type ContactPageQueryResult = {
  headline: string | null;
  intro: string | null;
  topics: Array<string> | null;
  successMessage: string | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: servicesQuery
// Query: *[_type == "service" && defined(slug.current)] | order(order asc, title asc){ _id, title, "slug": slug.current, summary, colorKey, coverStyle, order, deliverables }
export type ServicesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  order: number | null;
  deliverables: Array<string> | null;
}>;

// Source: src/sanity/queries.ts
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && slug.current == $slug][0]{    _id, title, "slug": slug.current, summary, colorKey, coverStyle, order, deliverables, body, seo, isSample  }
export type ServiceBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  colorKey: "accent" | "ink" | "mustard" | "plum" | "teal" | null;
  coverStyle:
    "bars" | "circles" | "line" | "rings" | "squares" | "triangle" | null;
  order: number | null;
  deliverables: Array<string> | null;
  body: RichText | null;
  seo: Seo | null;
  isSample: boolean | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: serviceSlugsQuery
// Query: *[_type == "service" && defined(slug.current)].slug.current
export type ServiceSlugsQueryResult = Array<string | null>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "reports": {\n    "total": count(*[_type == "report"]),\n    "recent": count(*[_type == "report" && _createdAt > $since]),\n    "previous": count(*[_type == "report" && _createdAt > $prevSince && _createdAt <= $since])\n  },\n  "articles": {\n    "total": count(*[_type == "article"]),\n    "recent": count(*[_type == "article" && _createdAt > $since]),\n    "previous": count(*[_type == "article" && _createdAt > $prevSince && _createdAt <= $since])\n  },\n  "services": {\n    "total": count(*[_type == "service"]),\n    "recent": count(*[_type == "service" && _createdAt > $since]),\n    "previous": count(*[_type == "service" && _createdAt > $prevSince && _createdAt <= $since])\n  },\n  "images": {\n    "total": count(*[_type == "sanity.imageAsset"]),\n    "recent": count(*[_type == "sanity.imageAsset" && _createdAt > $since]),\n    "previous": count(*[_type == "sanity.imageAsset" && _createdAt > $prevSince && _createdAt <= $since])\n  }\n}': AdminStatsQueryResult;
    '\n  *[_type in ["report", "article", "service", "author", "topic", "homePage", "aboutPage", "contactPage", "siteSettings", "sanity.imageAsset"] && _updatedAt > $since]{ _type, _updatedAt }\n': AdminActivityQueryResult;
    '\n  *[_type == "topic"]{\n    _id, title, colorKey,\n    "reports": count(*[_type == "report" && references(^._id)]),\n    "articles": count(*[_type == "article" && references(^._id)])\n  } | order((reports + articles) desc, title asc)\n': AdminTopicBreakdownQueryResult;
    '\n  *[_type in ["report", "article", "service", "author", "topic"]] | order(_updatedAt desc)[0...$limit]{ \n  _id, _type, _updatedAt, _createdAt,\n  "title": coalesce(title, name),\n  "slug": slug.current,\n  featured, isSample, publishedAt,\n  "topic": topic->{ title, colorKey },\n  "people": coalesce(authors[]->name, [author->name])\n }\n': AdminRecentQueryResult;
    '\n  *[_type == $type] | order(_updatedAt desc){ \n  _id, _type, _updatedAt, _createdAt,\n  "title": coalesce(title, name),\n  "slug": slug.current,\n  featured, isSample, publishedAt,\n  "topic": topic->{ title, colorKey },\n  "people": coalesce(authors[]->name, [author->name])\n, "count": count(*[references(^._id)]) }\n': AdminListQueryResult;
    '\n  *[_type == "sanity.imageAsset"] | order(_createdAt desc){\n    _id, url, originalFilename, size, extension, _createdAt,\n    "width": metadata.dimensions.width, "height": metadata.dimensions.height,\n    "usedBy": count(*[references(^._id)])\n  }\n': AdminMediaQueryResult;
    '\n  *[_id in ["homePage", "aboutPage", "contactPage", "siteSettings"]]{ _id, _type, _updatedAt }\n': AdminPagesQueryResult;
    '\n  *[_type in ["report", "article", "service", "author", "topic"] && [coalesce(title, name), pt::text(body), summary, excerpt, abstract] match $q]\n    | order(_updatedAt desc)[0...30]{ \n  _id, _type, _updatedAt, _createdAt,\n  "title": coalesce(title, name),\n  "slug": slug.current,\n  featured, isSample, publishedAt,\n  "topic": topic->{ title, colorKey },\n  "people": coalesce(authors[]->name, [author->name])\n }\n': AdminSearchQueryResult;
    '\n  coalesce(\n    *[_type == "report" && featured == true && defined(slug.current)] | order(publishedAt desc)[0],\n    *[_type == "report" && defined(slug.current)] | order(publishedAt desc)[0]\n  ){ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n, keyFindings, "pdfUrl": pdf.asset->url }\n': FeaturedReportQueryResult;
    '\n  *[_type == "report" && defined(slug.current)]\n    | order(publishedAt desc)[0...$limit]{ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': LatestReportsQueryResult;
    '\n  *[_type == "report" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n,\n    "topicId": topic._ref,\n    authors[]->{ _id, name, "slug": slug.current, role, photo, bio },\n    keyFindings,\n    body,\n    methodology,\n    sources,\n    "pdfUrl": pdf.asset->url,\n    seo,\n    isSample\n  }\n': ReportBySlugQueryResult;
    '\n  *[_type == "report" && topic->slug.current == $topic && defined(slug.current)]\n    | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': ReportsByTopicQueryResult;
    '\n  *[_type == "article" && defined(slug.current)]\n    | order(publishedAt desc)[0...$limit]{ \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n }\n': LatestArticlesQueryResult;
    '\n  *[_type == "article" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n,\n    "topicId": topic._ref,\n    author->{ _id, name, "slug": slug.current, role, photo, bio },\n    body,\n    seo,\n    isSample\n  }\n': ArticleBySlugQueryResult;
    '\n  *[_type == "topic"] | order(title asc){ _id, title, "slug": slug.current, colorKey, description }\n': AllTopicsQueryResult;
    '\n  *[_type == "report" && defined(slug.current) && (!defined($topic) || topic->slug.current == $topic)]\n    | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': ReportsListQueryResult;
    '\n  *[_type == "report" && defined(slug.current) && _id != $id && topic._ref == $topicId]\n    | order(publishedAt desc)[0...3]{ \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  abstract,\n  coverStyle,\n  publishedAt,\n  featured,\n  // Estimated from body length at ~220 words per minute.\n  "readTime": round(length(pt::text(body)) / 5 / 220) + 1,\n  topic->{ _id, title, "slug": slug.current, colorKey }\n }\n': RelatedReportsQueryResult;
    '\n  *[_type == "report" && defined(slug.current)].slug.current\n': ReportSlugsQueryResult;
    '\n  *[_type == "article" && defined(slug.current) && (!defined($topic) || topic->slug.current == $topic)]\n    | order(publishedAt desc){ \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n }\n': ArticlesListQueryResult;
    '\n  *[_type == "article" && defined(slug.current) && _id != $id]\n    | order(select(topic._ref == $topicId => 1, 0) desc, publishedAt desc)[0...3]{ \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  coverStyle,\n  publishedAt,\n  readTime,\n  featured,\n  topic->{ _id, title, "slug": slug.current, colorKey },\n  author->{ name, "slug": slug.current }\n }\n': RelatedArticlesQueryResult;
    '\n  *[_type == "article" && defined(slug.current)].slug.current\n': ArticleSlugsQueryResult;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    siteName, positioning, ctaLabel, email, phone, address, officeHours, socials[]{ _key, label, url }, copyright,\n    "capabilityPdfUrl": capabilityPdf.asset->url\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    eyebrow, headline, intro, primaryCta, secondaryCta, availability, trustFacts, marquee,\n    whoHeading, whoBody, whoQuote, whoQuoteAttribution,\n    founderQuote, founderName, founderRole,\n    numbersHeading, numbers[]{ _key, value, label },\n    commitmentsHeading, commitments[]{ _key, title, text },\n    statementHeading, statementText,\n    stepsHeading, steps[]{ _key, label, title, text },\n    ctaHeading, ctaText,\n    insightsHeading, servicesHeading, areasHeading, newsletterHeading, newsletterText, seo\n  }\n': HomePageQueryResult;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    headline, intro, story, values[]{ _key, title, text }, stats[]{ _key, value, label }, teamHeading,\n    team[]->{ _id, name, "slug": slug.current, role, photo, bio },\n    seo\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{ headline, intro, topics, successMessage, seo }\n': ContactPageQueryResult;
    '\n  *[_type == "service" && defined(slug.current)] | order(order asc, title asc){ _id, title, "slug": slug.current, summary, colorKey, coverStyle, order, deliverables }\n': ServicesQueryResult;
    '\n  *[_type == "service" && slug.current == $slug][0]{\n    _id, title, "slug": slug.current, summary, colorKey, coverStyle, order, deliverables, body, seo, isSample\n  }\n': ServiceBySlugQueryResult;
    '\n  *[_type == "service" && defined(slug.current)].slug.current\n': ServiceSlugsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
